//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouthAfricanSavingsWeb.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BodyP", Namespace="http://schemas.datacontract.org/2004/07/AugmentService")]
    [System.SerializableAttribute()]
    public partial class BodyP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PN {
            get {
                return this.PNField;
            }
            set {
                if ((object.ReferenceEquals(this.PNField, value) != true)) {
                    this.PNField = value;
                    this.RaisePropertyChanged("PN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qua {
            get {
                return this.QuaField;
            }
            set {
                if ((this.QuaField.Equals(value) != true)) {
                    this.QuaField = value;
                    this.RaisePropertyChanged("Qua");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SID {
            get {
                return this.SIDField;
            }
            set {
                if ((this.SIDField.Equals(value) != true)) {
                    this.SIDField = value;
                    this.RaisePropertyChanged("SID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sn {
            get {
                return this.SnField;
            }
            set {
                if ((this.SnField.Equals(value) != true)) {
                    this.SnField = value;
                    this.RaisePropertyChanged("Sn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/AugmentService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usertypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usertype {
            get {
                return this.usertypeField;
            }
            set {
                if ((object.ReferenceEquals(this.usertypeField, value) != true)) {
                    this.usertypeField = value;
                    this.RaisePropertyChanged("usertype");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ISearchService")]
    public interface ISearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Part", ReplyAction="http://tempuri.org/ISearchService/PartResponse")]
        bool Part(string ID, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Part", ReplyAction="http://tempuri.org/ISearchService/PartResponse")]
        System.Threading.Tasks.Task<bool> PartAsync(string ID, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/FindAugID", ReplyAction="http://tempuri.org/ISearchService/FindAugIDResponse")]
        int FindAugID(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/FindAugID", ReplyAction="http://tempuri.org/ISearchService/FindAugIDResponse")]
        System.Threading.Tasks.Task<int> FindAugIDAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/GetAug", ReplyAction="http://tempuri.org/ISearchService/GetAugResponse")]
        SouthAfricanSavingsWeb.ServiceReference.BodyP GetAug(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/GetAug", ReplyAction="http://tempuri.org/ISearchService/GetAugResponse")]
        System.Threading.Tasks.Task<SouthAfricanSavingsWeb.ServiceReference.BodyP> GetAugAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/EditAug", ReplyAction="http://tempuri.org/ISearchService/EditAugResponse")]
        bool EditAug(SouthAfricanSavingsWeb.ServiceReference.BodyP Aug, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/EditAug", ReplyAction="http://tempuri.org/ISearchService/EditAugResponse")]
        System.Threading.Tasks.Task<bool> EditAugAsync(SouthAfricanSavingsWeb.ServiceReference.BodyP Aug, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/NewPart", ReplyAction="http://tempuri.org/ISearchService/NewPartResponse")]
        bool NewPart(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/NewPart", ReplyAction="http://tempuri.org/ISearchService/NewPartResponse")]
        System.Threading.Tasks.Task<bool> NewPartAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/AddNewPart", ReplyAction="http://tempuri.org/ISearchService/AddNewPartResponse")]
        bool AddNewPart(SouthAfricanSavingsWeb.ServiceReference.BodyP p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/AddNewPart", ReplyAction="http://tempuri.org/ISearchService/AddNewPartResponse")]
        System.Threading.Tasks.Task<bool> AddNewPartAsync(SouthAfricanSavingsWeb.ServiceReference.BodyP p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Login", ReplyAction="http://tempuri.org/ISearchService/LoginResponse")]
        int Login(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Login", ReplyAction="http://tempuri.org/ISearchService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/GetUser", ReplyAction="http://tempuri.org/ISearchService/GetUserResponse")]
        SouthAfricanSavingsWeb.ServiceReference.User GetUser(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/GetUser", ReplyAction="http://tempuri.org/ISearchService/GetUserResponse")]
        System.Threading.Tasks.Task<SouthAfricanSavingsWeb.ServiceReference.User> GetUserAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Registered", ReplyAction="http://tempuri.org/ISearchService/RegisteredResponse")]
        bool Registered(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Registered", ReplyAction="http://tempuri.org/ISearchService/RegisteredResponse")]
        System.Threading.Tasks.Task<bool> RegisteredAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Register", ReplyAction="http://tempuri.org/ISearchService/RegisterResponse")]
        int Register(SouthAfricanSavingsWeb.ServiceReference.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Register", ReplyAction="http://tempuri.org/ISearchService/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(SouthAfricanSavingsWeb.ServiceReference.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Allbodyparts", ReplyAction="http://tempuri.org/ISearchService/AllbodypartsResponse")]
        SouthAfricanSavingsWeb.ServiceReference.BodyP[] Allbodyparts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchService/Allbodyparts", ReplyAction="http://tempuri.org/ISearchService/AllbodypartsResponse")]
        System.Threading.Tasks.Task<SouthAfricanSavingsWeb.ServiceReference.BodyP[]> AllbodypartsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchServiceChannel : SouthAfricanSavingsWeb.ServiceReference.ISearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchServiceClient : System.ServiceModel.ClientBase<SouthAfricanSavingsWeb.ServiceReference.ISearchService>, SouthAfricanSavingsWeb.ServiceReference.ISearchService {
        
        public SearchServiceClient() {
        }
        
        public SearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Part(string ID, string Name) {
            return base.Channel.Part(ID, Name);
        }
        
        public System.Threading.Tasks.Task<bool> PartAsync(string ID, string Name) {
            return base.Channel.PartAsync(ID, Name);
        }
        
        public int FindAugID(string ID) {
            return base.Channel.FindAugID(ID);
        }
        
        public System.Threading.Tasks.Task<int> FindAugIDAsync(string ID) {
            return base.Channel.FindAugIDAsync(ID);
        }
        
        public SouthAfricanSavingsWeb.ServiceReference.BodyP GetAug(string ID) {
            return base.Channel.GetAug(ID);
        }
        
        public System.Threading.Tasks.Task<SouthAfricanSavingsWeb.ServiceReference.BodyP> GetAugAsync(string ID) {
            return base.Channel.GetAugAsync(ID);
        }
        
        public bool EditAug(SouthAfricanSavingsWeb.ServiceReference.BodyP Aug, int ID) {
            return base.Channel.EditAug(Aug, ID);
        }
        
        public System.Threading.Tasks.Task<bool> EditAugAsync(SouthAfricanSavingsWeb.ServiceReference.BodyP Aug, int ID) {
            return base.Channel.EditAugAsync(Aug, ID);
        }
        
        public bool NewPart(string ID) {
            return base.Channel.NewPart(ID);
        }
        
        public System.Threading.Tasks.Task<bool> NewPartAsync(string ID) {
            return base.Channel.NewPartAsync(ID);
        }
        
        public bool AddNewPart(SouthAfricanSavingsWeb.ServiceReference.BodyP p) {
            return base.Channel.AddNewPart(p);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewPartAsync(SouthAfricanSavingsWeb.ServiceReference.BodyP p) {
            return base.Channel.AddNewPartAsync(p);
        }
        
        public int Login(string Email, string Password) {
            return base.Channel.Login(Email, Password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string Email, string Password) {
            return base.Channel.LoginAsync(Email, Password);
        }
        
        public SouthAfricanSavingsWeb.ServiceReference.User GetUser(int ID) {
            return base.Channel.GetUser(ID);
        }
        
        public System.Threading.Tasks.Task<SouthAfricanSavingsWeb.ServiceReference.User> GetUserAsync(int ID) {
            return base.Channel.GetUserAsync(ID);
        }
        
        public bool Registered(string Email, string Password) {
            return base.Channel.Registered(Email, Password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisteredAsync(string Email, string Password) {
            return base.Channel.RegisteredAsync(Email, Password);
        }
        
        public int Register(SouthAfricanSavingsWeb.ServiceReference.User u) {
            return base.Channel.Register(u);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(SouthAfricanSavingsWeb.ServiceReference.User u) {
            return base.Channel.RegisterAsync(u);
        }
        
        public SouthAfricanSavingsWeb.ServiceReference.BodyP[] Allbodyparts() {
            return base.Channel.Allbodyparts();
        }
        
        public System.Threading.Tasks.Task<SouthAfricanSavingsWeb.ServiceReference.BodyP[]> AllbodypartsAsync() {
            return base.Channel.AllbodypartsAsync();
        }
    }
}
